# Generated by Django 3.2.8 on 2021-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('AdministrativoId', models.AutoField(primary_key=True, serialize=False)),
                ('AdministrativoNombre', models.CharField(max_length=100)),
                ('Facultad', models.CharField(max_length=100)),
                ('FechaIngreso', models.DateField()),
                ('nombreFoto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('FacultadId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultadNombre', models.CharField(max_length=100)),
            ],
        ),
    ]
